### ISSUE TITLE
Canon EOS 700D slow --capture-movie

### ISSUE THREAD

**Issue by Esokrates** [gphoto/libgphoto2#482]
**Describe the bug**

I tried to use my EOS 700D as webcam by running

``` gphoto2 --capture-movie --stdout> fifo.mjpg ```

and view it with

```ffplay fifo.mjpg```

which is not fluent at all.

**Name the camera**
Canon EOS 700D

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

**Debuglog**

```
gphoto2 --auto-detect --debug
0.000249 main                        (2): ALWAYS INCLUDE THE FOLLOWING LINES WHEN SENDING DEBUG MESSAGES TO THE MAILING LIST:
0.000303 main                        (2): gphoto2 2.5.23
0.000320 main                        (2): gphoto2 has been compiled with the following options:
0.000337 main                        (2):  + gcc (C compiler used)
0.000347 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.000354 main                        (2):  + exif (for displaying EXIF information)
0.000360 main                        (2):  + cdk (for accessing configuration options)
0.000366 main                        (2):  + aa (for displaying live previews)
0.000372 main                        (2):  + jpeg (for displaying live previews in JPEG format)
0.000378 main                        (2):  + readline (for easy navigation in the shell)
0.000394 main                        (2): libgphoto2 2.5.23
0.000402 main                        (2): libgphoto2 has been compiled with the following options:
0.000409 main                        (2):  + all camlibs
0.000416 main                        (2):  + gcc (C compiler used)
0.000426 main                        (2):  + ltdl (for portable loading of camlibs)
0.000435 main                        (2):  + EXIF (for special handling of EXIF files)
0.000451 main                        (2): libgphoto2_port 0.12.0
0.000462 main                        (2): libgphoto2_port has been compiled with the following options:
0.000468 main                        (2):  + iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi
0.000474 main                        (2):  + gcc (C compiler used)
0.000480 main                        (2):  + ltdl (for portable loading of iolibs)
0.000487 main                        (2):  + USB (libusb1, for USB cameras)
0.000497 main                        (2):  + serial (for serial cameras)
0.000503 main                        (2):  + no resmgr (serial port access and locking)
0.000509 main                        (2):  + no ttylock (serial port locking)
0.000518 main                        (2):  + no lockdev (serial port locking)
0.000529 main                        (2): CAMLIBS env var not set, using compile-time default instead
0.000540 main                        (2): IOLIBS env var not set, using compile-time default instead
0.000550 main                        (2): invoked with following arguments:
0.000556 main                        (2):   --auto-detect
0.000566 main                        (2):   --debug
0.000600 load_settings               (2): Creating gphoto config directory ('/home/user/.gphoto')
0.000678 load_settings               (2): Loading settings from file '/home/user/.gphoto/settings'.
0.000910 gp_port_info_list_load      (2): Using ltdl to load io-drivers from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0'...
0.001043 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/disk'.
0.001467 gp_port_library_list        (2): found fstab fsname UUID=be0fafa9-2c93-4717-bc39-06d8bbf0a232
0.001497 gp_port_library_list        (2): found fstab fsname UUID=be0fafa9-2c93-4717-bc39-06d8bbf0a232
0.001514 gp_port_library_list        (2): found fstab fsname UUID=be0fafa9-2c93-4717-bc39-06d8bbf0a232
0.001530 gp_port_library_list        (2): found fstab fsname UUID=9b786c9e-5b9c-4651-bc7a-85faf191166c
0.001551 gp_port_library_list        (2): found fstab fsname UUID=08B1-A5AD
0.001577 gp_port_library_list        (2): found fstab fsname none
0.001603 gp_port_library_list        (2): found fstab fsname tmpfs
0.001627 gp_port_library_list        (2): found fstab fsname tmpfs
0.001652 gp_port_library_list        (2): found fstab fsname tmpfs
0.001800 gp_port_library_list        (2): found mtab fsname sysfs
0.001815 gp_port_library_list        (2): found mtab fsname proc
0.001823 gp_port_library_list        (2): found mtab fsname udev
0.001844 gp_port_library_list        (2): found mtab fsname devpts
0.001853 gp_port_library_list        (2): found mtab fsname tmpfs
0.001877 gp_port_library_list        (2): found mtab fsname /dev/sda8
0.001895 gp_port_library_list        (2): found mtab fsname securityfs
0.001903 gp_port_library_list        (2): found mtab fsname tmpfs
0.001921 gp_port_library_list        (2): found mtab fsname tmpfs
0.001942 gp_port_library_list        (2): found mtab fsname tmpfs
0.001970 gp_port_library_list        (2): found mtab fsname cgroup2
0.001982 gp_port_library_list        (2): found mtab fsname cgroup
0.001990 gp_port_library_list        (2): found mtab fsname pstore
0.002013 gp_port_library_list        (2): found mtab fsname efivarfs
0.002119 gp_port_library_list        (2): found mtab fsname none
0.002143 gp_port_library_list        (2): found mtab fsname cgroup
0.002154 gp_port_library_list        (2): found mtab fsname cgroup
0.002165 gp_port_library_list        (2): found mtab fsname cgroup
0.002177 gp_port_library_list        (2): found mtab fsname cgroup
0.002188 gp_port_library_list        (2): found mtab fsname cgroup
0.002198 gp_port_library_list        (2): found mtab fsname cgroup
0.002210 gp_port_library_list        (2): found mtab fsname cgroup
0.002221 gp_port_library_list        (2): found mtab fsname cgroup
0.002232 gp_port_library_list        (2): found mtab fsname cgroup
0.002243 gp_port_library_list        (2): found mtab fsname cgroup
0.002254 gp_port_library_list        (2): found mtab fsname cgroup
0.002314 gp_port_library_list        (2): found mtab fsname systemd-1
0.002326 gp_port_library_list        (2): found mtab fsname hugetlbfs
0.002350 gp_port_library_list        (2): found mtab fsname mqueue
0.002363 gp_port_library_list        (2): found mtab fsname debugfs
0.002387 gp_port_library_list        (2): found mtab fsname configfs
0.002413 gp_port_library_list        (2): found mtab fsname fusectl
0.002425 gp_port_library_list        (2): found mtab fsname tmpfs
0.002447 gp_port_library_list        (2): found mtab fsname tmpfs
0.002471 gp_port_library_list        (2): found mtab fsname tmpfs
0.002493 gp_port_library_list        (2): found mtab fsname /dev/sda1
0.002515 gp_port_library_list        (2): found mtab fsname /dev/sda8
0.002533 gp_port_library_list        (2): found mtab fsname /dev/sda8
0.002550 gp_port_library_list        (2): found mtab fsname tracefs
0.002584 gp_port_library_list        (2): found mtab fsname tmpfs
0.002609 gp_port_library_list        (2): found mtab fsname /dev/fuse
0.002620 gp_port_library_list        (2): found mtab fsname /dev/fuse
0.002688 foreach_func                (2): Loaded '' ('^disk:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/disk'.
0.002702 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/ptpip'.
0.003080 foreach_func                (2): Loaded 'PTP/IP Connection' ('ptpip:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/ptpip'.
0.003098 foreach_func                (2): Loaded '' ('^ptpip:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/ptpip'.
0.003107 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003596 foreach_func                (2): Loaded 'Serial Port 0' ('serial:/dev/ttyS0') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003614 foreach_func                (2): Loaded 'Serial Port 1' ('serial:/dev/ttyS1') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003622 foreach_func                (2): Loaded 'Serial Port 2' ('serial:/dev/ttyS2') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003631 foreach_func                (2): Loaded 'Serial Port 3' ('serial:/dev/ttyS3') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003639 foreach_func                (2): Loaded 'Serial Port 4' ('serial:/dev/ttyS4') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003647 foreach_func                (2): Loaded 'Serial Port 5' ('serial:/dev/ttyS5') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003655 foreach_func                (2): Loaded 'Serial Port 6' ('serial:/dev/ttyS6') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003674 foreach_func                (2): Loaded 'Serial Port 7' ('serial:/dev/ttyS7') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003687 foreach_func                (2): Loaded 'Serial Port 8' ('serial:/dev/ttyS8') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003695 foreach_func                (2): Loaded 'Serial Port 9' ('serial:/dev/ttyS9') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003703 foreach_func                (2): Loaded 'Serial Port 10' ('serial:/dev/ttyS10') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003711 foreach_func                (2): Loaded 'Serial Port 11' ('serial:/dev/ttyS11') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003719 foreach_func                (2): Loaded 'Serial Port 12' ('serial:/dev/ttyS12') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003728 foreach_func                (2): Loaded 'Serial Port 13' ('serial:/dev/ttyS13') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003739 foreach_func                (2): Loaded 'Serial Port 14' ('serial:/dev/ttyS14') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003753 foreach_func                (2): Loaded 'Serial Port 15' ('serial:/dev/ttyS15') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003764 foreach_func                (2): Loaded 'Serial Port 16' ('serial:/dev/ttyS16') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003775 foreach_func                (2): Loaded 'Serial Port 17' ('serial:/dev/ttyS17') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003787 foreach_func                (2): Loaded 'Serial Port 18' ('serial:/dev/ttyS18') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003798 foreach_func                (2): Loaded 'Serial Port 19' ('serial:/dev/ttyS19') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003810 foreach_func                (2): Loaded 'Serial Port 20' ('serial:/dev/ttyS20') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003822 foreach_func                (2): Loaded 'Serial Port 21' ('serial:/dev/ttyS21') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003833 foreach_func                (2): Loaded 'Serial Port 22' ('serial:/dev/ttyS22') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003845 foreach_func                (2): Loaded 'Serial Port 23' ('serial:/dev/ttyS23') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003856 foreach_func                (2): Loaded 'Serial Port 24' ('serial:/dev/ttyS24') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003867 foreach_func                (2): Loaded 'Serial Port 25' ('serial:/dev/ttyS25') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003879 foreach_func                (2): Loaded 'Serial Port 26' ('serial:/dev/ttyS26') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003890 foreach_func                (2): Loaded 'Serial Port 27' ('serial:/dev/ttyS27') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003901 foreach_func                (2): Loaded 'Serial Port 28' ('serial:/dev/ttyS28') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003912 foreach_func                (2): Loaded 'Serial Port 29' ('serial:/dev/ttyS29') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003924 foreach_func                (2): Loaded 'Serial Port 30' ('serial:/dev/ttyS30') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003935 foreach_func                (2): Loaded 'Serial Port 31' ('serial:/dev/ttyS31') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003947 foreach_func                (2): Loaded 'Serial Port Device' ('serial:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003960 foreach_func                (2): Loaded '' ('^serial:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/serial'.
0.003971 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usb1'.
0.010170 foreach_func                (2): Loaded '' ('^usb:') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usb1'.
0.010204 foreach_func                (2): Loaded 'Universal Serial Bus' ('usb:001,002') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usb1'.
0.010214 foreach_func                (2): Loaded 'Universal Serial Bus' ('usb:001,022') from '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usb1'.
0.010223 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usbdiskdirect'.
0.010659 foreach_func                (2): Called for filename '/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0/usbscsi'.
0.011015 gp_port_info_list_count     (2): Counting entries (40 available)...
0.011027 gp_port_info_list_count     (2): 36 regular entries available.
0.011034 gp_port_info_list_count     (2): Counting entries (40 available)...
0.011040 gp_port_info_list_count     (2): 36 regular entries available.
0.011080 gp_abilities_list_load_dir  (2): Using ltdl to load camera libraries from '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23'...
0.011199 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/ax203'.
0.011215 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/canon'.
0.011222 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/digigr8'.
0.011229 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/dimagev'.
0.011236 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/directory'.
0.011243 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/jl2005a'.
0.011249 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/jl2005c'.
0.011256 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/kodak_dc240'.
0.011263 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/mars'.
0.011269 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/pentax'.
0.011276 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/ptp2'.
0.011282 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/sierra'.
0.011289 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/sonix'.
0.011295 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/sq905'.
0.011302 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/st2205'.
0.011308 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/topfield'.
0.011314 foreach_func                (2): Found '/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.23/tp6801'.
0.011324 gp_abilities_list_load_dir  (2): Found 17 camera drivers.
0.037943 gp_port_info_list_count     (2): Counting entries (40 available)...   
0.037960 gp_port_info_list_count     (2): 36 regular entries available.
0.037964 gp_port_new                 (2): Creating new device...
0.037969 gp_port_info_list_get_info  (2): Getting info of entry 0 (40 available)...
0.038126 gp_port_set_settings        (2): Setting settings...
0.038135 gp_port_info_list_get_info  (2): Getting info of entry 1 (40 available)...
0.038247 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038253 gp_port_set_settings        (2): Setting settings...
0.038256 gp_port_info_list_get_info  (2): Getting info of entry 2 (40 available)...
0.038341 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038347 gp_port_set_settings        (2): Setting settings...
0.038350 gp_port_info_list_get_info  (2): Getting info of entry 3 (40 available)...
0.038428 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038434 gp_port_set_settings        (2): Setting settings...
0.038437 gp_port_info_list_get_info  (2): Getting info of entry 4 (40 available)...
0.038514 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038520 gp_port_set_settings        (2): Setting settings...
0.038526 gp_port_info_list_get_info  (2): Getting info of entry 5 (40 available)...
0.038604 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038610 gp_port_set_settings        (2): Setting settings...
0.038615 gp_port_info_list_get_info  (2): Getting info of entry 6 (40 available)...
0.038691 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038697 gp_port_set_settings        (2): Setting settings...
0.038702 gp_port_info_list_get_info  (2): Getting info of entry 7 (40 available)...
0.038778 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038785 gp_port_set_settings        (2): Setting settings...
0.038789 gp_port_info_list_get_info  (2): Getting info of entry 8 (40 available)...
0.038866 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038873 gp_port_set_settings        (2): Setting settings...
0.038876 gp_port_info_list_get_info  (2): Getting info of entry 9 (40 available)...
0.038952 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.038958 gp_port_set_settings        (2): Setting settings...
0.038963 gp_port_info_list_get_info  (2): Getting info of entry 10 (40 available)...
0.039039 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039045 gp_port_set_settings        (2): Setting settings...
0.039051 gp_port_info_list_get_info  (2): Getting info of entry 11 (40 available)...
0.039126 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039133 gp_port_set_settings        (2): Setting settings...
0.039137 gp_port_info_list_get_info  (2): Getting info of entry 12 (40 available)...
0.039212 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039219 gp_port_set_settings        (2): Setting settings...
0.039223 gp_port_info_list_get_info  (2): Getting info of entry 13 (40 available)...
0.039299 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039305 gp_port_set_settings        (2): Setting settings...
0.039310 gp_port_info_list_get_info  (2): Getting info of entry 14 (40 available)...
0.039388 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039394 gp_port_set_settings        (2): Setting settings...
0.039399 gp_port_info_list_get_info  (2): Getting info of entry 15 (40 available)...
0.039477 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039483 gp_port_set_settings        (2): Setting settings...
0.039488 gp_port_info_list_get_info  (2): Getting info of entry 16 (40 available)...
0.039564 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039570 gp_port_set_settings        (2): Setting settings...
0.039573 gp_port_info_list_get_info  (2): Getting info of entry 17 (40 available)...
0.039646 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039650 gp_port_set_settings        (2): Setting settings...
0.039653 gp_port_info_list_get_info  (2): Getting info of entry 18 (40 available)...
0.039725 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039732 gp_port_set_settings        (2): Setting settings...
0.039736 gp_port_info_list_get_info  (2): Getting info of entry 19 (40 available)...
0.039813 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039819 gp_port_set_settings        (2): Setting settings...
0.039822 gp_port_info_list_get_info  (2): Getting info of entry 20 (40 available)...
0.039905 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.039911 gp_port_set_settings        (2): Setting settings...
0.039918 gp_port_info_list_get_info  (2): Getting info of entry 21 (40 available)...
0.039999 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040006 gp_port_set_settings        (2): Setting settings...
0.040011 gp_port_info_list_get_info  (2): Getting info of entry 22 (40 available)...
0.040095 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040102 gp_port_set_settings        (2): Setting settings...
0.040107 gp_port_info_list_get_info  (2): Getting info of entry 23 (40 available)...
0.040195 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040203 gp_port_set_settings        (2): Setting settings...
0.040210 gp_port_info_list_get_info  (2): Getting info of entry 24 (40 available)...
0.040307 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040313 gp_port_set_settings        (2): Setting settings...
0.040315 gp_port_info_list_get_info  (2): Getting info of entry 25 (40 available)...
0.040394 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040400 gp_port_set_settings        (2): Setting settings...
0.040404 gp_port_info_list_get_info  (2): Getting info of entry 26 (40 available)...
0.040481 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040487 gp_port_set_settings        (2): Setting settings...
0.040490 gp_port_info_list_get_info  (2): Getting info of entry 27 (40 available)...
0.040563 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040568 gp_port_set_settings        (2): Setting settings...
0.040574 gp_port_info_list_get_info  (2): Getting info of entry 28 (40 available)...
0.040647 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040652 gp_port_set_settings        (2): Setting settings...
0.040656 gp_port_info_list_get_info  (2): Getting info of entry 29 (40 available)...
0.040728 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040734 gp_port_set_settings        (2): Setting settings...
0.040737 gp_port_info_list_get_info  (2): Getting info of entry 30 (40 available)...
0.040868 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040874 gp_port_set_settings        (2): Setting settings...
0.040897 gp_port_info_list_get_info  (2): Getting info of entry 31 (40 available)...
0.040967 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.040973 gp_port_set_settings        (2): Setting settings...
0.040976 gp_port_info_list_get_info  (2): Getting info of entry 32 (40 available)...
0.041039 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.041045 gp_port_set_settings        (2): Setting settings...
0.041049 gp_port_info_list_get_info  (2): Getting info of entry 33 (40 available)...
0.041114 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.041119 gp_port_set_settings        (2): Setting settings...
0.041123 gp_port_info_list_get_info  (2): Getting info of entry 34 (40 available)...
0.043169 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.043177 gp_port_set_settings        (2): Setting settings...
0.043185 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,002, (new int=0, conf=-1, alt=-1) port usb:001,002
0.043188 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.043191 gp_abilities_list_detect_usb(2): Auto-detecting USB cameras...
0.043592 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x29a, subclass, 0xffffffff, protocol 0xffffffff)...
0.043893 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x6, subclass, 0x1, protocol 0x1)...
0.043923 gp_port_info_list_get_info  (2): Getting info of entry 35 (40 available)...
0.046006 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.046073 gp_port_set_settings        (2): Setting settings...
0.046081 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,022, (new int=0, conf=-1, alt=-1) port usb:001,022
0.046085 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.046112 gp_abilities_list_detect_usb(2): Auto-detecting USB cameras...
0.046220 gp_libusb1_find_device_lib  (2): Looking for USB device (vendor 0x4a9, product 0x3272)... found.
0.046251 gp_libusb1_find_device_lib  (2): Detected defaults: config 1, interface 0, altsetting 0, inep 81, outep 02, intep 83, class 06, subclass 01
0.046254 gp_abilities_list_detect_usb(2): Found 'Canon EOS 700D' (0x4a9,0x3272)
0.046267 gp_port_free                (2): Freeing port...
0.046270 gp_port_close               (2): Closing port...
Model                          Port            
----------------------------------------------------------
Canon EOS 700D                 usb:001,022     
0.046680 gp_camera_free              (2): Freeing camera...
0.046685 gp_port_free                (2): Freeing port...
0.046688 gp_filesystem_reset         (2): resetting filesystem
0.046691 gp_filesystem_lru_clear     (2): Clearing fscache LRU list...
0.046693 gp_filesystem_lru_clear     (2): fscache LRU list already empty
0.046697 delete_all_folders          (2): Internally deleting all folders from '/'...
0.046699 lookup_folder               (2): Lookup folder '/'...
0.046701 lookup_folder               (2): Found! / is 0x56440129a8c0
0.046705 recurse_delete_folder       (2): Recurse delete folder 0x56440129a8c0//
```

**Comment by msmeissn** [comment]
hmm, not fluent... if you record to file with just capture-movie and then play it, is it better?

This kind of viewing is really hackish though.  

Does it work better if you use e.g. "entangle" ?

**Comment by tomato42** [comment]
it if fluid if you run `gphoto2 --capture-movie --stdout | ffplay -`?

**Comment by Esokrates** [comment]
@msmeissn, @tomato42 Due to COVID19 it will take some time for me to get access to the camera and test again, so please be patient.

**Comment by msmeissn** [comment]
No worries, this can wait :) Stay safe!

**Comment by Esokrates** [comment]
> @Esokrates is it fluid if you run `gphoto2 --capture-movie --stdout | ffplay -`?

No it's stuttering unfortunately.



> hmm, not fluent... if you record to file with just capture-movie and then play it, is it better?

I couldn't play the file movie.mjpg, it opens up just as picture.
I recorded for at least over 10 seconds but it just reported 76 frames being captured.

**Comment by tomato42** [comment]
> > @Esokrates is it fluid if you run `gphoto2 --capture-movie --stdout | ffplay -`?
> 
> No it's stuttering unfortunately.

did you try different cable or different port? (maybe it's negotiating USB 1.1 speeds instead of USB 2.0)

> > hmm, not fluent... if you record to file with just capture-movie and then play it, is it better?
> 
> I couldn't play the file movie.mjpg, it opens up just as picture.
> I recorded for at least over 10 seconds but it just reported 76 frames being captured.

try using  ffplay to play it (`ffplay movie.mjpeg`)

**Comment by Esokrates** [comment]
@tomato42 I just have one cable, apart from that All my Ports are USB 3.0 / Thunderbird.
Playing the file with ffplay looks like fast forwarding a movie, it plays way too fast, any idea here?

Do you have the same camera and it works for you?

**Comment by tomato42** [comment]
all USB 3.0 ports can negotiate USB 2.0 and even USB 1.1 speeds (in fact all mice and keyboards use USB 1.1 speeds only), including the USB-C ports. When you are copying data off of the SD card inside camera, what speeds you're getting?

if it plays too fast that indicates that the frames got dropped

I have 750D and yes, it works fine for me (fluid and lag no worse than the built-in webcam)

**Comment by msmeissn** [comment]
I debugged this, and we had some logic that caused a much lower framerate than wanted.

**Comment by mre** [comment]
Thanks for your work @msmeissn.
Tried the latest version by compiling from source. (Only recompiled libgphoto2, not gphoto2 as that shouldn't be necessary AFAICT).

```
❯❯❯ gphoto2 --version
gphoto2 2.5.23

Copyright (c) 2000-2019 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23         clang, popt(m), no exif, no cdk, no aa, jpeg, readline
libgphoto2      2.5.25         standard camlibs, clang, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, clang, ltdl, no EXIF, USB, serial without locking
```

Ran `time gphoto2 --capture-movie` and kept it running for 1:21.29min. It captured 813 frames. That's an odd number considering that that's exactly 10.0fps. 

Am I doing something wrong and still using the old version?
If not, I wonder if we cap the framerate somewhere and that's the upper bound.

**Comment by msmeissn** [comment]
2.5.25 still has the timing bug... It only is fixed in current libgphoto2 master.

I am planning to do a 2.5.26 soonish in the next weeks.

**Comment by msmeissn** [comment]
you can try do 
gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null 
and see if it it gets mpore than 100 frames ,)

**Comment by mre** [comment]
Thanks, here's what I get:

```
gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (84 frames)
```

Any way I can test the fix before the official release? I was compiling from `master` (commit 21147cc4152ff1d276d9dd236de2e777b686ef18). Think that should contain the fix.
For a test, I was manually bumping the version to 2.5.26 in `configure.ac:8`. After compiling, `gphoto` still shows 2.5.25, so I must be missing something...

**Comment by msmeissn** [comment]
gphoto2 --version   should show 2.5.25.1 ...   check if you have the correct --prefix and --libdir during configure

**Comment by mre** [comment]
You mean during configure of gphoto2, right? Still using the version from brew, which is probably the reason why it doesn't work. Compilation didn't work when I tried:

```
Undefined symbols for architecture x86_64:
  "_rl_copy_text", referenced from:
      _shell_completion_function in gphoto2-shell.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gphoto2] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I think that's because of missing readline dev headers, but I'll have to find out how to install them on macOS.

**Comment by mre** [comment]
Okay I found [this post](http://harvey.nu/compiling_gphoto2-2.4.8_snow_leopard.html) and `./configure --without-readline` did the trick!

**Comment by mre** [comment]
```
❯❯❯ gphoto2 --version
gphoto2 2.5.23.1

Copyright (c) 2000-2020 Marcus Meissner and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.23.1       gcc, popt(m), no exif, no cdk, no aa, jpeg, no readline
libgphoto2      2.5.25.1       standard camlibs, gcc, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, no EXIF, USB, serial without locking
```

In "camera" mode:

```
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (88 frames)

gphoto2 on  master took 11s
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (90 frames)

gphoto2 on  master took 10s
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (92 frames)
```

In movie mode:
```
gphoto2 on  master took 10s
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (137 frames)

gphoto2 on  master took 10s
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (135 frames)

gphoto2 on  master took 10s
❯❯❯ gphoto2 --capture-movie=10s --debug --debug-logfile=/dev/null
Capturing preview frames as movie to 'movie.mjpg' for 10 seconds.
Movie capture finished (134 frames)
```

**Comment by msmeissn** [comment]
hmm. not much difference so far. :/

**Comment by mre** [comment]
Attached a debug file created with
```
gphoto2 --capture-movie=10s --debug --debug-loglevel=debug --debug-logfile=debug.txt
```

[debug.txt](https://github.com/gphoto/libgphoto2/files/4780576/debug.txt)

**Comment by mre** [comment]
Did some measurements on my Linux desktop machine as well.
Ubuntu 18.04 LTS, AMD FX(tm)-6300 Six-Core Processor 3.5GHz, 12GB RAM
Made a couple of measurments and the results are the same at 134 frames on average.

The debug log is... a bit long, so I split it up into multiple files and provide just the beginning and the very end here.

[debug00.txt](https://github.com/gphoto/libgphoto2/files/4783371/debug00.txt)
[debug01.txt](https://github.com/gphoto/libgphoto2/files/4783373/debug01.txt)
[debug02.txt](https://github.com/gphoto/libgphoto2/files/4783374/debug02.txt)
[debug9281.txt](https://github.com/gphoto/libgphoto2/files/4783377/debug9281.txt)

In hindsight I could have used a shorter recording duration but ¯\_(ツ)_/¯.
Let me know if you want me to move the conversation elsewhere. Don't want to spam a closed ticket. ;)

**Comment by sim590** [comment]
What are the final results on this ? I have the same camera and still experiencing 134 frames per 10s in video mode which is not high enough IMO compared to others having things like 60 fps. I'm on version 2.5.26.

**Comment by mre** [comment]
I haven't found a solution either. Still hoping for a patch to improve the situation.
In my opinion the issue should be reopened.

**Comment by msmeissn** [comment]
I changed the wait log a bit.

For me its kind of different:

- EOS 100D - 13FPS still
- EOS 1000D - around 20FPS
- EOS 750D - 25 - 30 FPS

**Comment by sim590** [comment]
Also, when I configure my Canon EOS 700D to capture video with configuration `1280x720, 60FPS`, in the camera menus I'm getting even worse performance: 5FPS by running `gphoto2 --capture-movie=100s`.
